# Generated by Django 3.1.1 on 2020-09-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_text', models.CharField(max_length=40)),
                ('pick_type', models.CharField(max_length=40)),
                ('pts', models.CharField(max_length=40)),
                ('Pick_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
