# Generated by Django 3.1.1 on 2020-09-10 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='Pick_date',
        ),
        migrations.AddField(
            model_name='pick',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
